remote_theme: just-the-docs/just-the-docs@v0.4.0 

# Загальні налаштування
title: Документація ППУ-М
description: Інструкції з обслуговування та експлуатації.
lang: uk
color_scheme: dark

# Налаштування пошуку
search_enabled: true
# -- Налаштування індексування для пошуку (Lunr) --
lunr:
  content: true # Включати вміст сторінок
  title: true   # Включати заголовки сторінок
  keywords: true # Включати ключові слова
  titles: true  # Включати заголовки вбудовані у текст сторінок

# Налаштування навігації
nav_external_links:
  - title: GitHub Repo
    url: https://github.com/jupeppa/ppu_docu
